


export enum IDepartment {
    // ACADEMIC = 'Academic',
    // ACCOUNTS = 'Accounts & Finance',
    // ESTABLISHMENT = 'Establishment',
    // PROCUREMENT = 'Procurement',
    // CHEMISTRY='Chemistry'
    DIRECTOR = "Director office",
    DEAN_ACADEMIC = "Dean(Academic)",
    DEAN_FACULTY = "Dean(Faculty Welfare)",
    DEAN_STUDENT = "Dean(Student Welfare)",
    DEAN_PLANNING = "Dean(Planning & Development)",
    DEAN_REASEARCH = "Dean(Research & Consultancy)",
    REGISTRAR_OFFICE = "Registrar office",
    ESTABLISHMENT = "Establishment & Administration",
    EXAM_SECTION = "Exam Section",
    FINANCE = "Finance & Accounts",
    PROCUREMENT = "Procurement",
    ESTATE = "Esate Service Unit",
    ELECTRICAL_MAINTENANCE = "Electrical Maintenance Unit",
    CENTRAL_LIBRARY = "Central Library",
    SECURITY = "Security Office",
    HEALTH_CENTRE = "Health Centre",
    TRANING_PLACEMENT = "Training & Placement",
    IT_SERVICE = "IT Service",
    WEBSITE_MIS = "Website & MIS Office",
    HOSTEL_MANAGEMENT = "Hostel Management Committee",
    DEPT_ARCHITECTURE = "Department of Architecture & Planning",
    DEPT_CIVIL = "Department of Civil Engineering",
    DEPT_COMPUTER = "Department of Computer Science Engineering",
    DEPT_ELECTRICAL = "Department of Electrical Engineering",
    DEPT_ELECTRONICS = "Department of Electronics and Communication Engineering",
    DEPT_MECHANICAL = "Department of Mechanical Engineering",
    DEPT_PHYSICS = "Department of Physics",
    DEPT_CHEMISTRY = "Department of Chemistry",
    DEPT_MATHEMATICS = "Department of Mathematics",
    DEPT_HUMANITIES = "Department of Humanities & Social Science",
    CWRS = "CWRS",
    COMPUTER_CENTRE = "Computer Centre",
    E_ICT = "E&ICT Academy",
}



export enum IShortDepartment {
    // ACADEMIC = 'AC',
    // ACCOUNTS = 'AF',
    // ESTABLISHMENT = 'ES',
    // PROCUREMENT = 'PR',
    // CHEMISTRY='CH'
    DIRECTOR = "DO",
    DEAN_ACADEMIC = "DA",
    DEAN_FACULTY = "DFW",
    DEAN_STUDENT = "DSW",
    DEAN_PLANNING = "DPD",
    DEAN_REASEARCH = "DRC",
    REGISTRAR_OFFICE = "RO",
    ESTABLISHMENT = "EA",
    EXAM_SECTION = "EX",
    FINANCE = "F&A",
    PROCUREMENT = "PR",
    ESTATE = "ESU",
    ELECTRICAL_MAINTENANCE = "EMU",
    CENTRAL_LIBRARY = "CL",
    SECURITY = "SO",
    HEALTH_CENTRE = "HC",
    TRANING_PLACEMENT = "T&P",
    IT_SERVICE = "IT",
    WEBSITE_MIS = "MIS",
    HOSTEL_MANAGEMENT = "HMC",
    DEPT_ARCHITECTURE = "A&PD",
    DEPT_CIVIL = "CED",
    DEPT_COMPUTER = "CSED",
    DEPT_ELECTRICAL = "EED",
    DEPT_ELECTRONICS = "ECED",
    DEPT_MECHANICAL = "MED",
    DEPT_PHYSICS = "Phy",
    DEPT_CHEMISTRY = "Chem",
    DEPT_MATHEMATICS = "Math",
    DEPT_HUMANITIES = "HSS",
    CWRS = "CWRS",
    COMPUTER_CENTRE = "CC",
    E_ICT = "E&ICT",
}





export const ActiveDepartments = [
    // IDepartment.ACADEMIC,
    // IDepartment.ACCOUNTS,
    // IDepartment.CHEMISTRY,
    // IDepartment.ESTABLISHMENT,
    // IDepartment.PROCUREMENT


    IDepartment.CENTRAL_LIBRARY,
    IDepartment.ELECTRICAL_MAINTENANCE,
    IDepartment.ESTATE,
    IDepartment.FINANCE,
    IDepartment.REGISTRAR_OFFICE,
    IDepartment.DEAN_REASEARCH,
    IDepartment.DEAN_STUDENT,
    IDepartment.DEAN_PLANNING,
    IDepartment.DEAN_ACADEMIC,
    IDepartment.DEAN_FACULTY,
    IDepartment.DIRECTOR,
    IDepartment.ESTABLISHMENT,
    IDepartment.DEPT_CIVIL,
    IDepartment.DEPT_ARCHITECTURE,
    IDepartment.HOSTEL_MANAGEMENT,
    IDepartment.WEBSITE_MIS,
    IDepartment.IT_SERVICE,
    IDepartment.TRANING_PLACEMENT,
    IDepartment.HEALTH_CENTRE,
    IDepartment.SECURITY,
    IDepartment.E_ICT,
    IDepartment.COMPUTER_CENTRE,
    IDepartment.DEPT_HUMANITIES,
    IDepartment.CWRS,
    IDepartment.DEPT_MATHEMATICS,
    IDepartment.DEPT_CHEMISTRY,
    IDepartment.DEPT_PHYSICS,
    IDepartment.DEPT_MECHANICAL,
    IDepartment.DEPT_ELECTRONICS,
    IDepartment.DEPT_ELECTRICAL,
    IDepartment.DEPT_COMPUTER,
    IDepartment.PROCUREMENT,
    IDepartment.EXAM_SECTION,

]
export const shortNameDepartment = [
    IShortDepartment.CENTRAL_LIBRARY,
    IShortDepartment.ELECTRICAL_MAINTENANCE,
    IShortDepartment.ESTATE,
    IShortDepartment.FINANCE,
    IShortDepartment.REGISTRAR_OFFICE,
    IShortDepartment.DEAN_REASEARCH,
    IShortDepartment.DEAN_STUDENT,
    IShortDepartment.DEAN_PLANNING,
    IShortDepartment.DEAN_ACADEMIC,
    IShortDepartment.DEAN_FACULTY,
    IShortDepartment.DIRECTOR,
    IShortDepartment.ESTABLISHMENT,
    IShortDepartment.DEPT_CIVIL,
    IShortDepartment.DEPT_ARCHITECTURE,
    IShortDepartment.HOSTEL_MANAGEMENT,
    IShortDepartment.WEBSITE_MIS,
    IShortDepartment.IT_SERVICE,
    IShortDepartment.TRANING_PLACEMENT,
    IShortDepartment.HEALTH_CENTRE,
    IShortDepartment.SECURITY,
    IShortDepartment.E_ICT,
    IShortDepartment.COMPUTER_CENTRE,
    IShortDepartment.DEPT_HUMANITIES,
    IShortDepartment.CWRS,
    IShortDepartment.DEPT_MATHEMATICS,
    IShortDepartment.DEPT_CHEMISTRY,
    IShortDepartment.DEPT_PHYSICS,
    IShortDepartment.DEPT_MECHANICAL,
    IShortDepartment.DEPT_ELECTRONICS,
    IShortDepartment.DEPT_ELECTRICAL,
    IShortDepartment.DEPT_COMPUTER,
    IShortDepartment.PROCUREMENT,
    IShortDepartment.EXAM_SECTION,
]