export const tableKeys= ["REGN_NO", "SGPA",
        "SUB1NM", "SUB1", "SUB1_GRADE", "SUB1_GRADE_POINTS", "SUB1_CREDIT", "SUB1_CREDIT_POINTS", "SUB1_TYPE",
        "SUB2NM", "SUB2", "SUB2_GRADE", "SUB2_GRADE_POINTS", "SUB2_CREDIT", "SUB2_CREDIT_POINTS", "SUB2_TYPE",
        "SUB3NM", "SUB3", "SUB3_GRADE", "SUB3_GRADE_POINTS", "SUB3_CREDIT", "SUB3_CREDIT_POINTS", "SUB3_TYPE",
        "SUB4NM", "SUB4", "SUB4_GRADE", "SUB4_GRADE_POINTS", "SUB4_CREDIT", "SUB4_CREDIT_POINTS", "SUB4_TYPE",
        "SUB5NM", "SUB5", "SUB5_GRADE", "SUB5_GRADE_POINTS", "SUB5_CREDIT", "SUB5_CREDIT_POINTS", "SUB5_TYPE",
        "SUB6NM", "SUB6", "SUB6_GRADE", "SUB6_GRADE_POINTS", "SUB6_CREDIT", "SUB6_CREDIT_POINTS", "SUB6_TYPE",
        "SUB7NM", "SUB7", "SUB7_GRADE", "SUB7_GRADE_POINTS", "SUB7_CREDIT", "SUB7_CREDIT_POINTS", "SUB7_TYPE",
        "SUB8NM", "SUB8", "SUB8_GRADE", "SUB8_GRADE_POINTS", "SUB8_CREDIT", "SUB8_CREDIT_POINTS", "SUB8_TYPE",
        "SUB9NM", "SUB9", "SUB9_GRADE", "SUB9_GRADE_POINTS", "SUB9_CREDIT", "SUB9_CREDIT_POINTS", "SUB9_TYPE",
        "SUB10NM", "SUB10", "SUB10_GRADE", "SUB10_GRADE_POINTS", "SUB10_CREDIT", "SUB10_CREDIT_POINTS", "SUB10_TYPE",
        "SUB11NM", "SUB11", "SUB11_GRADE", "SUB11_GRADE_POINTS", "SUB11_CREDIT", "SUB11_CREDIT_POINTS", "SUB11_TYPE"
      ]
